theme = "minimal"
baseURL = "/"
languageCode = "en-us"
title = "Alex Handy"

[params]
    author = "Alex Handy"
    description = "Researching dementia prediction and treatment at King’s College London using multi-omics and data science."
    githubUsername = "AlexHandy1"
    accent = "red"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 2

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 3

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.


[[menu.icon]]
    url = "https://github.com/AlexHandy1"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://www.linkedin.com/in/alex-handy-926342a/"
    name = "linkedin"
    weight = 3
